import { PLAYER_HEIGHT } from './constants.js';

const H = PLAYER_HEIGHT * 0.5;
const H_TALL = PLAYER_HEIGHT * 0.58;
const H_SMALL = PLAYER_HEIGHT * 0.48;
const H_MED = PLAYER_HEIGHT * 0.54;

export const MOB_TYPES = {
  zombie: {
    name: 'Зомби',
    hostile: true,
    width: 0.58,
    height: H_TALL,
    speed: 18,
    damage: 7,
    hp: 24,
    chaseRange: 12,
    attackCooldown: 1.4,
    spawnWeight: 4,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'zombie',
    },
  },
  skeleton: {
    name: 'Скелет',
    hostile: true,
    width: 0.56,
    height: H_TALL,
    speed: 20,
    damage: 6,
    hp: 18,
    chaseRange: 13,
    attackCooldown: 1.6,
    spawnWeight: 3,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'skeleton',
    },
  },
  boar: {
    name: 'Кабан',
    hostile: false,
    flee: true,
    width: 1.05,
    height: H_MED,
    speed: 26,
    damage: 4,
    hp: 16,
    chaseRange: 0,
    fleeRange: 8,
    attackCooldown: 0.8,
    spawnWeight: 4,
    parts: {
      drawOrder: ['leg', 'leg', 'tail', 'body', 'head'],
      prefix: 'boar',
    },
  },
  fox: {
    name: 'Лиса',
    hostile: false,
    flee: true,
    width: 1.1,
    height: H_SMALL,
    speed: 30,
    damage: 3,
    hp: 10,
    chaseRange: 0,
    fleeRange: 10,
    attackCooldown: 0.6,
    spawnWeight: 5,
    parts: {
      drawOrder: ['leg', 'leg', 'tail', 'body', 'ear', 'head'],
      prefix: 'fox',
    },
  },
  gnome: {
    name: 'Гном',
    hostile: false,
    width: 0.55,
    height: H,
    speed: 16,
    damage: 2,
    hp: 14,
    chaseRange: 0,
    attackCooldown: 0.5,
    spawnWeight: 3,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'gnome',
    },
  },
  alien: {
    name: 'Пришелец',
    hostile: false,
    width: 0.62,
    height: H,
    speed: 20,
    damage: 3,
    hp: 15,
    chaseRange: 0,
    attackCooldown: 0.7,
    spawnWeight: 2,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'alien',
    },
  },
  hedgehog: {
    name: 'Ёж',
    hostile: false,
    flee: true,
    width: 0.85,
    height: H_SMALL * 0.85,
    speed: 22,
    damage: 2,
    hp: 8,
    chaseRange: 0,
    fleeRange: 6,
    attackCooldown: 0.5,
    spawnWeight: 5,
    single: 'hedgehog_body',
  },
};

export const MOB_TYPE_IDS = Object.keys(MOB_TYPES);
