export const MOB_TYPES = {
  zombie: {
    name: 'Зомби',
    hostile: true,
    width: 0.52,
    height: 1.45,
    speed: 22,
    damage: 14,
    hp: 45,
    chaseRange: 14,
    attackCooldown: 1.1,
    spawnWeight: 4,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'zombie',
    },
  },
  skeleton: {
    name: 'Скелет',
    hostile: true,
    width: 0.5,
    height: 1.45,
    speed: 25,
    damage: 11,
    hp: 35,
    chaseRange: 16,
    attackCooldown: 1.3,
    spawnWeight: 3,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'skeleton',
    },
  },
  boar: {
    name: 'Кабан',
    hostile: false,
    flee: true,
    width: 0.85,
    height: 0.75,
    speed: 30,
    damage: 8,
    hp: 30,
    chaseRange: 0,
    fleeRange: 8,
    attackCooldown: 0.8,
    spawnWeight: 4,
    parts: {
      drawOrder: ['leg', 'leg', 'tail', 'body', 'head'],
      prefix: 'boar',
    },
  },
  fox: {
    name: 'Лиса',
    hostile: false,
    flee: true,
    width: 0.9,
    height: 0.55,
    speed: 34,
    damage: 5,
    hp: 18,
    chaseRange: 0,
    fleeRange: 10,
    attackCooldown: 0.6,
    spawnWeight: 5,
    parts: {
      drawOrder: ['leg', 'leg', 'tail', 'body', 'ear', 'head'],
      prefix: 'fox',
    },
  },
  gnome: {
    name: 'Гном',
    hostile: false,
    width: 0.45,
    height: 1.05,
    speed: 18,
    damage: 4,
    hp: 25,
    chaseRange: 0,
    attackCooldown: 0.5,
    spawnWeight: 3,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'gnome',
    },
  },
  alien: {
    name: 'Пришелец',
    hostile: false,
    width: 0.55,
    height: 1.35,
    speed: 24,
    damage: 6,
    hp: 28,
    chaseRange: 0,
    attackCooldown: 0.7,
    spawnWeight: 2,
    parts: {
      drawOrder: ['leg', 'leg', 'body', 'arm', 'head'],
      prefix: 'alien',
    },
  },
  hedgehog: {
    name: 'Ёж',
    hostile: false,
    flee: true,
    width: 0.7,
    height: 0.45,
    speed: 26,
    damage: 3,
    hp: 12,
    chaseRange: 0,
    fleeRange: 6,
    attackCooldown: 0.5,
    spawnWeight: 5,
    single: 'hedgehog_body',
  },
};

export const MOB_TYPE_IDS = Object.keys(MOB_TYPES);
